# Generated by Django 3.1 on 2020-08-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=4096)),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
